### PR TITLE
proposal: Ignore `vendor` directory

### PR DESCRIPTION
**Pull request by candiduslynx**
### Description
Please explain the changes you made here.

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by candiduslynx** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by candiduslynx** [comment]
recheck

**Comment by sfc-gh-dszmolka** [comment]
https://github.com/snowflakedb/gosnowflake/issues/729

**Comment by candiduslynx** [comment]
@sfc-gh-dszmolka any chance of review/running the workflows?

**Comment by sfc-gh-dszmolka** [comment]
PRs posted in this repo are regularly reviewed by the driver team, cannot promise any estimated timeline though. Thank you for bearing with us !

**Comment by sfc-gh-igarish** [comment]
could you please add more details about this PR?

**Comment by candiduslynx** [comment]
Hi @sfc-gh-igarish!

The reasoning could be linked to #729.
 
Basically, it's not required to save the `vendor` inside the repo unless the codebase has some manual updates (replaces, etc).

Additionally, having this lot of files results in huge updates when it should've been only a small commit.
Example: #769

**Comment by zeroshade** [comment]
I agree with this personally! It will make updates of dependencies significantly easier going forward if we can get rid of the vendor directory entirely.

**Comment by candiduslynx** [comment]
@sfc-gh-igarish is there a chance to get this reviewed/merged?
One of the reasons for this proposal can be seen at the moment (conflicts over simple vendor changes, that should've been scoped to `go.mod` & `go.sum` files only)
image

**Comment by candiduslynx** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by candiduslynx** [comment]
Hi @sfc-gh-igarish! Any chance on reviewing this?

**Comment by zeroshade** [comment]
@candiduslynx they will probably ask you to rebase this back up-to-date. So can you pre-emptively do that and let's hope we can get their attention :smile:

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM

**Comment by candiduslynx** [comment]
@sfc-gh-igarish thanks for the review!
Do I need to do something special to make CLA pass?

**Pull request merged**
