### PR TITLE
Snow 146214/add insecure mode to dsn

### PR DESCRIPTION
**Pull request by s-baron**
### Description
Before, the DSN function wasn't actually adding InsecureMode to the string. Update so it does if insecuremode is true

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by snowstakeda** [comment]
FYI, changed the target branch to prep-1.3.5

**Comment by snowstakeda** [comment]
@jaewanbahk , this is already approved, but please take a quick look to learn the code.

**Comment by snowstakeda** [comment]
@s-baron when do you want us to release this fix in the prod? Can we wait for your further changes?

**Comment by s-baron** [comment]
There's no hurry on my end - sorry if I merged prematurely! Can wait til whenever

**Pull request merged**
