### PR TITLE
Check if the context deadline is exceeded when retrying in the snowflakeChunkDownloader

### PR DESCRIPTION
**Pull request by grindlemire**
### Description
Ensures the `snowflakeChunkDownloader` respects context deadlines like other areas of the code

### CODE REVIEW

**Comment by grindlemire** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by grindlemire** [comment]
recheck

**Review by sfc-gh-ext-simba-lb — APPROVED** [review]
LGTM

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM

**Comment by sfc-gh-ext-simba-lb** [comment]
@grindlemire Could you please update the branch. Thanks!

**Pull request merged**
