### PR TITLE
Rebase 2021 06 14

### PR DESCRIPTION
**Pull request by luke-zhu**
### Description
Please explain the changes you made here.

### Checklist
- [ ] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [ ] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by luke-zhu** [comment]
`make lint` fails for me

```
/home/luke/gosnowflake/export.go:5:1: comment on exported type ExecResponse should be of the form "ExecResponse ..." (with optional leading article)
/home/luke/gosnowflake/export.go:7:6: exported type ExecResponseRowType should have comment or be unexported
/home/luke/gosnowflake/export.go:8:6: exported type ExecResponseChunk should have comment or be unexported
/home/luke/gosnowflake/export.go:9:6: exported type SnowflakeRows should have comment or be unexported
/home/luke/gosnowflake/export.go:10:6: exported type SnowflakeRestful should have comment or be unexported
/home/luke/gosnowflake/export.go:11:6: exported type SnowflakeValue should have comment or be unexported
/home/luke/gosnowflake/export.go:12:6: exported type ChunkRowType should have comment or be unexported
/home/luke/gosnowflake/export.go:13:6: exported type SimpleTokenAccessor should have comment or be unexported
/home/luke/gosnowflake/export.go:17:5: exported var ArrowToValue should have comment or be unexported
/home/luke/gosnowflake/observe.go:10:2: a blank import should be only in a main or test package, or have a comment justifying it
/home/luke/gosnowflake/observe.go:15:2: comment on exported const ResponseBodyLimit should be of the form "ResponseBodyLimit ..."
/home/luke/gosnowflake/observe.go:19:5: exported var ErrResponseTooLarge should have comment or be unexported
Found 12 lint suggestions; failing.
```

**Comment by luke-zhu** [comment]
```
=== RUN   TestBindingArray
    driver_test.go:282: error on exec [insert into TEST_PREP_STATEMENT values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]: 100114 (22000): The following string is not a legal base64-encoded value: '010203'
--- FAIL: TestBindingArray (1.41s)
=== RUN   TestBindingBulkArray
    bindings_test.go:301: 001006 (22023): SQL compilation error:
        invalid parameter 'CLIENT_STAGE_ARRAY_BINDING_THRESHOLD'
--- FAIL: TestBindingBulkArray (1.17s)
```

**Comment by sfc-gh-jbahk** [comment]
Hi I'm not sure what the purpose of PR is -- we don't have an export.go file and the failing test is an internal parameter test that we purposely safeguard.

**Comment by luke-zhu** [comment]
damn wrong repo

**Pull request closed without merging**
