### PR TITLE
Revert go-ieproxy back to version 0.0.1

### PR DESCRIPTION
**Pull request by sfc-gh-ext-simba-lb**
### Description
As part of #663, the go-ieproxy library was upgraded from 0.0.1 to 0.0.9. 

#681 reported issues with version 0.0.9 when using the Go driver with terraform provider. We can't remove the library because it is an indirect dependency used by direct dependency github.com/Azure/azure-storage-blob-go.

### Checklist
- [ ] Code compiles correctly
- [ ] Run ``make fmt`` to fix inconsistent formats
- [ ] Run ``make lint`` to get lint errors and fix all of them
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by sfc-gh-igarish** [comment]
Was the upgrade related to a security issue? Does it mean we never able to upgrade?

**Comment by sfc-gh-ext-simba-lb** [comment]
> Was the upgrade related to a security issue? Does it mean we never able to upgrade?

No, we upgraded all dependencies in the previous release, this one did not have a security issue. 

I found the issue is reported on the go-ieproxy repository: https://github.com/mattn/go-ieproxy/issues/45
We won't be able to upgrade until this is resolved.

**Comment by sfc-gh-igarish** [comment]
> > Was the upgrade related to a security issue? Does it mean we never able to upgrade?
> 
> @sfc-gh-igarish No, we upgraded all dependencies in the previous release, this one did not have a security issue.
> 
> I found the issue is reported on the go-ieproxy repository: [mattn/go-ieproxy#45](https://github.com/mattn/go-ieproxy/issues/45) We won't be able to upgrade until this is resolved.

Ok. so how to track the actual issue of upgrade? Can you create another ticket to track it?

**Comment by sfc-gh-ext-simba-lb** [comment]
> [mattn/go-ieproxy#45](https://github.com/mattn/go-ieproxy/issues/45)

I created issue #690.

**Pull request merged**
