### PR TITLE
Cleanup of auth.go

### PR DESCRIPTION
**Pull request by tjj5036**
### Description
This is a followup to an earlier PR. The authenticator connection parameter should be used in auth.go, rather than inferring the authenticator from the values passed in.

Tested via setting connection parameters in `parameters.json` and running `make test`.

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by smtakeda** [comment]
Looks great! thanks you!

**Comment by smtakeda** [comment]
@tjj5036 Do you want me to add a release tag including the recent changes? If you are planning to do the public preview of OAuth support, it should have a release.

**Comment by tjj5036** [comment]
That's a good question - regarding external browser authentication, I think that should have a release tag. I would hold off on OAuth at the moment.

**Comment by smtakeda** [comment]
ok. I should have noticed that time... Realized that I would need to bump up the version in version.go as well. Is it ok to add v1.1.5 to the latest commit along with version.go change but not to mention OAuth in release note?

**Comment by tjj5036** [comment]
Sounds good!

**Pull request merged**
