### PR TITLE
SNOW-209087: Update log framework to use logrus. Allow replacing logg…

### PR DESCRIPTION
**Pull request by sfc-gh-cshi**
…er from outside of driver

    glog does not support structured logs and the current default logger is printing no logs. To switch to printing logs requires
    another build flag which is not suitable for enterprise(production) usage.
    This change is to use logrus to replace glog, so we could actually have 'Error', 'Warning', 'Info' and 'Debug' levels
    in log messages, structured logs.
    Other changes include setting logging levels accordingly in all logging places.
    Add cmd/logger. Add required vendors for logrus

Testing: Local 'make' tests all pass

### Description
Introduce SFLogger interface to expose FieldLogger from logrus with additional APIs needed. Replace glog logging to use proper log level defined in logrus.

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [ ] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by sfc-gh-stakeda — APPROVED** [review]
Looks good to me. Just resolve the merge conflict.

**Comment by sfc-gh-jbahk** [comment]
@sfc-gh-cshi did we get this vendor approved by security?

**Comment by sfc-gh-stakeda** [comment]
One suggestion. After merging this, it would probably be better bumping up the minor version to include this change, because this is not a trivial bug fix according to https://semver.org/. It is up you how you translate the change, though. Please work with @ankit-bhatnagar167 . Thanks.

**Comment by sfc-gh-anezvigin** [comment]
The logger is still global which means we won't be able to push state through the call stack. The way we solve this problem is by attaching our structured logger state to the `context.Context` object and extracting in places such as `retryHTTP()`.

**Comment by sfc-gh-cshi** [comment]
> The logger is still global which means we won't be able to push state through the call stack. The way we solve this problem is by attaching our structured logger state to the `context.Context` object and extracting in places such as `retryHTTP()`.

Adding and passing context to logs will be addressed in another PR/JIRA this week. This PR now is for log framework update, not a trivial one already.

**Pull request merged**
