### PR TITLE
improve: use context.Background instead of context.TODO

### PR DESCRIPTION
**Pull request by sivchari**
### Description
I changed context.TODO to context.Background. context.Background equals context.TODO, so this change doesn't affect to any libs. But it's clear that the current implementation uses context, so we should use context.Background instead of context.TODO.

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by sfc-gh-pfus** [comment]
Thank you @sivchari  for your suggestion! You are obviously right. Can you rebase and solve conflicts?

**Comment by sivchari** [comment]
@sfc-gh-pfus 
I fixed it. Thanks for review 😄

**Comment by sfc-gh-pfus** [comment]
Thank you @sivchari ! Is there any particular reason why you left this occurrences?

```
❯ grep -ir 'context.TODO'
./auth_test.go: _, err = authenticate(context.TODO(), sc, []byte{}, []byte{})
./auth_test.go: _, err = authenticate(context.TODO(), sc, []byte{}, []byte{})
./auth_test.go: _, err = authenticate(context.TODO(), sc, []byte{}, []byte{})
./auth_test.go: sc.ctx = context.TODO()
./auth_test.go: _, err = authenticate(context.TODO(), sc, []byte{}, []byte{})
./auth_test.go: _, err = authenticate(context.TODO(), sc, []byte{}, []byte{})
./auth_test.go: _, err = authenticate(context.TODO(), sc, []byte{}, []byte{})
./retry_test.go:        _, err = newRetryHTTP(context.TODO(),
./retry_test.go:        _, err = newRetryHTTP(context.TODO(),
./retry_test.go:        _, err = newRetryHTTP(context.TODO(),
./retry_test.go:        _, err = newRetryHTTP(context.TODO(),
./authexternalbrowser_test.go:  _, _, err := authenticateByExternalBrowser(context.TODO(), sr, authenticator, application, account, user, password, timeout)
./authexternalbrowser_test.go:  _, _, err = authenticateByExternalBrowser(context.TODO(), sr, authenticator, application, account, user, password, timeout)
./authexternalbrowser_test.go:  _, _, err = authenticateByExternalBrowser(context.TODO(), sr, authenticator, application, account, user, password, timeout)
./authexternalbrowser_test.go:  _, _, err := authenticateByExternalBrowser(context.TODO(), sr, authenticator, application, account, user, password, timeout)
❯ grep -ir 'context.TODO' | wc -l
      15
```

**Comment by sivchari** [comment]
I overlooked. I'll fix these args.

**Comment by sivchari** [comment]
@sfc-gh-pfus 
I fixed it.

**Review by sfc-gh-pfus — APPROVED** [review]

**Comment by sfc-gh-pfus** [comment]
Thanks a lot @sivchari for your PR! I merged it.

**Pull request merged**
