### PR TITLE
fix: goroutine leak

### PR DESCRIPTION
**Pull request by sivchari**
### Description
I fixed goroutine leaks.

releted with #588

- Close Body.
- Close Idle connections, if close db.  

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by dominicbarnes** [comment]
I was recently troubleshooting a goroutine leak that failed exactly like this, it would be great for this fix to land.

**Comment by sivchari** [comment]
ping @sfc-gh-jbahk

**Comment by sivchari** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-jbahk** [comment]
Closing as duplicate.

**Pull request closed without merging**
