### PR TITLE
Update dependencies, fix conflicts with other packages

### PR DESCRIPTION
**Pull request by kenshaw**
### Description

Changes arrow to v11, updates all dependencies, and removes replace statements within go.mod, as these cause conflicts/issues when importing this package.

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [N/A] Created tests which fail without the change (if possible)
- [x] All tests passing
- [N/A] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by kenshaw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kenshaw** [comment]
Submitting this PR as there are conflicts with Snowflake's dependency on the older `arrow` version with other drivers (which also make use of `arrow) in [`usql`](https://github.com/xo/usql). 

I would humbly request/suggest that this package drop the `vendor` directory, as it would be much preferable if dependencies (like database drivers) left this up to the project incorporating the package.

**Comment by zeroshade** [comment]
The failure here:
image
appears to be an issue on the CI side, rather than an issue with the actual change/diffs here. Could this please get looked at and expedited?

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM

**Comment by sfc-gh-igarish** [comment]
Please update the branch.

**Comment by zeroshade** [comment]
@kenshaw can you please update / rebase this branch? This should get merged before my #769 does

**Comment by kenshaw** [comment]
@zeroshade done.

**Comment by zeroshade** [comment]
@sfc-gh-igarish branch is updated! please merge at your earliest convenience!

**Comment by sfc-gh-igarish** [comment]
Still waiting for test to finish and pass.

**Comment by zeroshade** [comment]
The tests that failed in the CI don't appear to be anything related to this change as far as I can tell (unless there are other tests that are running but that aren't publicly visible on here?)

image

It looks like the issue is something with the config and secret key?

**Comment by kenshaw** [comment]
@zeroshade I would assume that's because this is PR, and those secrets are available for PRs.

**Comment by sfc-gh-igarish** [comment]
ok. I get your PR and created a new PR on top of it. Let's see how tests goes now.

**Pull request merged**
