### PR TITLE
Upgrade AWS SDK packages to the latest version

### PR DESCRIPTION
**Pull request by evan-bradley**
### Description

Hello!

I am a maintainer on a project that uses the Go Snowflake driver to ingest data from snowflake: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/snowflakereceiver#snowflake-receiver

We recently discovered that another module in our application uses a newer version of the Go AWS SDK library which appears to have type changes that conflict with the version used here. This PR upgrades the library to the latest version without introducing any code changes. I was unable to run any tests locally due to the setup required, but I did compile our application with a replace statement that links to these changes to determine that the code still builds. I will rely on CI to determine that everything still works, but can do the necessary setup to test locally if there are issues.

### Checklist
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by evan-bradley** [comment]
I'm reaching out internally about signing the CLA. I will mark this PR as a draft until I get confirmation I can sign it.

**Comment by sfc-gh-pfus** [comment]
Hi @evan-bradley ! Thank you for your contribution. We can wait for your confirmation on CLA and in the meantime I started CI builds. You can observe results. Stay tuned!

**Comment by evan-bradley** [comment]
Thank you for taking a look @sfc-gh-pfus! Unfortunately, I don't think I will hear back in time to make a change this small worth the wait. I'm going to close this and the upgrades can be done in https://github.com/snowflakedb/gosnowflake/pull/1126, or a follow-up from you or another contributor. It appears CI is green for everything but the CLA check, so I think the upgrades should be smooth. Thanks again.

**Comment by sfc-gh-pfus** [comment]
Thank you @evan-bradley for your attempt to make gosnowflake better! As we already have everything we need, I'll merge #1126 .

**Pull request closed without merging**
