### PR TITLE
SNOW-183506 Drop support of Go 1.13

### PR DESCRIPTION
**Pull request by sfc-gh-jbahk**
### Description
Removed Go 1.13 tests in line with dropping support for Go 1.13.

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by sfc-gh-stakeda — APPROVED** [review]

**Comment by sfc-gh-abhatnagar** [comment]
@smtakeda Should I force merge this PR as  the tests passed but probably the merge gate is is `master` so 1.13 is not running https://github.com/snowflakedb/gosnowflake/actions/runs/302901396 ?

**Comment by sfc-gh-stakeda** [comment]
Looks like the merge needs to update. btw, my account is @sfc-gh-stakeda

**Comment by sfc-gh-stakeda** [comment]
Removed 1.13 jobs and added 1.15 jobs to the merge gate.

**Comment by sfc-gh-jbahk** [comment]
@sfc-gh-stakeda Is there something I can do regarding this? Should I push again?

**Pull request merged**
