### PR TITLE
Make the documentation godoc-friendly

### PR DESCRIPTION
**Pull request by igungor**
### Description
It's sad to see that https://godoc.org/github.com/snowflakedb/gosnowflake package is not the best looking package documentation right now. This PR is an attempt to make this package godoc-friendly.

I'm not sure if it's OK with you about moving all documentation from README to the package domain but I think it's very convenient since the tooling around the editors are using godoc (in the form of `go doc`).

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [ ] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by smtakeda** [comment]
Alright. Honestly I was not aware that the doc was already generated and published. Let me play with this and understand how it is supposed to be. Thanks for PR!

**Comment by igungor** [comment]
Sure.

**Comment by smtakeda** [comment]
Ok, I figured how to run godoc locally and check the results:
* godoc -http=:6060
* http://localhost:6060/pkg/github.com/snowflakedb/gosnowflake/

**Comment by smtakeda** [comment]
Fixed minor doc issues. https://github.com/snowflakedb/gosnowflake/tree/pr-118
@igungor can you please review the change?

**Comment by igungor** [comment]
Changes look good to me. Thanks!

**Pull request merged**
