### PR TITLE
Fix checking the identical errors

### PR DESCRIPTION
**Pull request by igungor**
### Description

left and right handside of the comparison are identical. These types of typos/errors are easily be spotted with a static analyzer.

What do you think about adding such a tool to CI?

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [ ] Created tests which fail without the change (if possible)
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by smtakeda** [comment]
Ah, thanks for reporting a bug. What tool would you recommend? Will look into the options.

**Comment by smtakeda** [comment]
Adding https://goreportcard.com/report/github.com/snowflakedb/gosnowflake to README.rst

**Comment by igungor** [comment]
gometalinter is very popular but my I use [megacheck](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck) after before every commit.

**Comment by smtakeda** [comment]
Thanks. I'm adding megacheck to lint target. See https://github.com/snowflakedb/gosnowflake/pull/120

**Pull request merged**
